CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_INPUT=y
CONFIG_LOG=y
CONFIG_INPUT_LOG_LEVEL_WRN=y
CONFIG_DISPLAY=y
CONFIG_MIPI_DBI=y
CONFIG_GC9X01X=y
CONFIG_INPUT_CST8XX=y
CONFIG_LVGL=y
#2 bytes per pixel, keep 2 for now change later/for more speed switching screens
CONFIG_LV_COLOR_DEPTH_16=y
#color is inverted so invert it back
CONFIG_LV_COLOR_16_SWAP=y 
#set buffer size to 50% of the display, so 240x240x2bytes/pixel = 115200 bytes/2 = 57600 bytes
CONFIG_LV_Z_VDB_SIZE=50 
#use two video buffers
CONFIG_LV_Z_DOUBLE_VDB=y 
#and flush the display
CONFIG_LV_Z_FLUSH_THREAD=y 
CONFIG_LV_Z_MEM_POOL_SIZE=16384
CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_LV_USE_LOG=y
CONFIG_LV_LOG_LEVEL_INFO=y